language: go
go:
- '1.10'
- master
install: true
matrix:
  allow_failures:
  - go: master
  fast_finish: true
notifications:
  email: false
before_script:
- go get -u github.com/golang/dep/cmd/dep
script:
- make dev-dependencies
- make test
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: bin/*
  on:
    repo: politie/sseserver
